### ISSUE TITLE
have version of key that doesn't try to put itself on the window

### ISSUE THREAD

**Issue by scamden** [adlawson/coffee-key#1]
if i use key with browserify i love the containment i normally get without putting required modules onto the window. is it possible to build a key_node.js file that doesn't attempt to put itself on the window? let me know if you're down and i could submit a pr

**Comment by adlawson** [comment]
Hey,
This library is something I've been meaning to either fix up or deprecate for some time.
It's something I wrote a _long_ time ago; way before the days of browserify.

I will make changes in time to properly support all environments, but for now I think it would be best for you to simply fork the project and use that instead.

**Comment by scamden** [comment]
ok no problem, out of curiosity why deprecate? are there other problems?

On 7 October 2014 13:30, Andrew Lawson notifications@github.com wrote:

> Hey,
> This library is something I've been meaning to either fix up or deprecate
> for some time.
> It's something I wrote a _long_ time ago; way before the days of
> browserify.
> 
> I will make changes in time to properly support all environments, but for
> now I think it would be best for you to simply fork the project and use
> that instead for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adlawson/key/issues/1#issuecomment-58255992.

## 

_Sterling Camden_
Software Engineer
502 Emerson Street | Palo Alto, CA 94301
303.520.2968 | sterling@relateiq.com

See RelateIQ in the _Wall Street Journal
http://online.wsj.com/news/articles/SB10001424127887323949904578539983425941490,_
TechCrunch
http://techcrunch.com/2013/06/12/relateiq-launches-with-29m-from-formation-8-dustin-moskovitz-and-more-to-be-your-next-gen-relationship-manager/,
Forbes
http://www.forbes.com/sites/michaelsimmons/2014/01/14/the-one-thing-you-should-do-after-meeting-anyone-new/,
and More http://blog.relateiq.com/tag/relateiqinthenews/!

**Comment by adlawson** [comment]
It's just a project that I haven't maintained, so I suppose my options are either to update it and keep it updated or deprecate it in favour of a more maintained project.

My aim is to fix it up, but failing that I'll probably deprecate it (still keep it available but add notes to the fact that it won't ever be updated)
